---
- name: Set permanent DNS on Ubuntu without changing interface
  hosts: all
  become: true
  vars:
    dns_servers:
      - 8.8.8.8
      - 1.1.1.1
    netplan_config: "/etc/netplan/00-installer-config.yaml"

  tasks:
    - name: Backup existing Netplan config
      copy:
        src: "{{ netplan_config }}"
        dest: "{{ netplan_config }}.bak"
        remote_src: yes
