---
- name: Set permanent DNS on Ubuntu without changing interface
  hosts: ubuntu_servers
  become: true
  vars:
    dns_servers:
      - 8.8.8.8
      - 1.1.1.1
    netplan_config: "/etc/netplan/00-installer-config.yaml"  # Adjust if needed

  tasks:
    - name: Backup existing Netplan config
      copy:
        src: "{{ netplan_config }}"
        dest: "{{ netplan_config }}.bak"
        remote_src: yes

    - name: Insert or update nameservers section under existing interface
      blockinfile:
        path: "{{ netplan_config }}"
        marker: "# {mark} ANSIBLE MANAGED DNS"
        block: |
          nameservers:
            addresses:
            {% for dns in dns_servers %}
              - {{ dns }}
            {% endfor %}
        insertafter: '^\s+dhcp4:.*'   # This assumes dhcp4 or static config already exists

    - name: Apply Netplan
      command: netplan apply
