---
- name: Update only DNS servers in netplan config (Ubuntu)
  hosts: all
  become: true
  vars:
    netplan_file_path: "/etc/netplan/01-netcfg.yaml"  # Change if your netplan file is different
    new_dns_block: |
      addresses:
        - 1.1.1.1
        - 8.8.8.8

  tasks:
    - name: Replace DNS addresses in netplan config
      replace:
        path: "{{ netplan_file_path }}"
        regexp: '^\s*addresses:\n(\s*-\s.*\n)+'
        replace: "{{ new_dns_block | indent(6, false) }}"
      notify: Apply netplan

  handlers:
    - name: Apply netplan
      command: netplan apply
