---
- name: Update DNS servers in netplan YAML
  hosts: all
  become: true
  vars:
    netplan_file: /etc/netplan/00-installer-config.yaml
    new_dns:
      - 1.1.1.1
      - 8.8.8.8

  tasks:
    - name: Replace DNS addresses block in netplan
      replace:
        path: "{{ netplan_file }}"
        # Match the block starting with "addresses:" under "nameservers:"
        regexp: '(nameservers:\n\s*addresses:\n)(\s*-\s.*\n)+'
        # Replace with the new DNS list properly indented (6 spaces)
        replace: "{{ 'nameservers:\n      addresses:\n' + (new_dns | map('regex_replace', '(.*)', '        - \\1') | join('\n')) + '\n' }}"
      notify: Apply netplan

  handlers:
    - name: Apply netplan
      command: netplan apply
