---
- name: Show network and DNS configuration on Linux systems
  hosts: all
  gather_facts: yes

  vars:
    dns_file: "/etc/resolv.conf"

  tasks:

    - name: Get network interface IP addresses
      set_fact:
        ip_report: >-
          {% set ip_list = [] %}
          {% for iface in ansible_interfaces %}
            {% set iface_data = hostvars[inventory_hostname]['ansible_' + iface] %}
            {% if iface_data is defined and iface_data.ipv4 is defined %}
              {% set _ = ip_list.append(iface + ' - ' + iface_data.ipv4.address) %}
            {% endif %}
          {% endfor %}
          {{ ip_list | join(', ') }}

    - name: Get DNS settings from /etc/resolv.conf
      ansible.builtin.shell: cat {{ dns_file }}
      register: resolv_conf
      changed_when: false

    - name: Show network and DNS config for each host
      debug:
        msg: |
          ==== Network & DNS Info ====
          Hostname: {{ ansible_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          IPs: {{ ip_report }}
          DNS Config (/etc/resolv.conf):
          {{ resolv_conf.stdout }}
