---
- name: Ping all Linux hosts and collect status
  hosts: all
  gather_facts: no
  tasks:

    - name: Ping the host
      ansible.builtin.ping:
      register: ping_result
      ignore_errors: yes

    - name: Set CSV line for each host
      set_fact:
        ping_info_line: "{{ inventory_hostname }},{{ 'REACHABLE' if ping_result is succeeded else 'UNREACHABLE' }}"

- name: Combine Ping CSV Report on Controller
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    csv_file_path: "./ping_reachability_report.csv"
    email_recipient: "m.jahangir.alam@ucb.com.bd"
    smtp_host: "172.23.18.26"
    smtp_port: 465
    smtp_user: "ansible@upay.systems"
    smtp_password: "Upay@321"
  tasks:

    - name: Build CSV from all hosts
      set_fact:
        csv_report: |
          Host,Reachability
          {% for host in groups['all'] %}
          {{ hostvars[host].ping_info_line | default(host + ',UNKNOWN') }}
          {% endfor %}

    - name: Save CSV to file
      copy:
        content: "{{ csv_report }}"
        dest: "{{ csv_file_path }}"

    - name: Send CSV report as email attachment
      community.general.mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user }}"
        password: "{{ smtp_password }}"
        to: "{{ email_recipient }}"
        subject: "Ping Reachability CSV Report"
        body: "Please find attached the ping reachability status report in CSV format."
        attach:
          - "{{ csv_file_path }}"
        secure: always
