---
- name: Check connectivity of all Linux hosts
  hosts: all
  gather_facts: no
  tasks:

    - name: Ping the host
      ansible.builtin.ping:
      register: ping_result
      ignore_errors: yes

    - name: Set host status fact
      set_fact:
        host_status: "{{ 'REACHABLE' if ping_result is succeeded else 'UNREACHABLE' }}"

    - name: Add host status to global dict on localhost
      run_once: true
      delegate_to: localhost
      set_fact:
        all_hosts_status: "{{ (all_hosts_status | default({})) | combine({inventory_hostname: host_status}) }}"

- name: Pass all_hosts_status fact to localhost for emailing
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Add all_hosts_status fact to localhost hostvars
      add_host:
        name: localhost
        all_hosts_status: "{{ hostvars['localhost'].all_hosts_status | default({}) }}"

- name: Send connectivity report email (CSV format)
  hosts: localhost
  gather_facts: no
  vars:
    email_recipient: "recipient@example.com"
    email_subject: "Ping Connectivity Report - CSV Format"
  tasks:

    - name: Generate CSV formatted report
      set_fact:
        csv_report: |
          host,status
          {% for host, status in hostvars['localhost'].all_hosts_status.items() %}
          {{ host }},{{ status }}
          {% endfor %}

    - name: Send email with CSV connectivity report
      community.general.mail:
        host: 172.23.18.26
        port: 465
        username: ansible@upay.systems
        password: Upay@321
        to: m.jahangir.alam@ucb.com.bd
        subject: "{{ email_subject }}"
        body: "{{ csv_report }}"
        secure: always
        subtype: "csv"
