---
- name: Check connectivity of all Linux hosts
  hosts: all
  gather_facts: no
  tasks:

    - name: Ping the host
      ansible.builtin.ping:
      register: ping_result
      ignore_errors: yes

    - name: Set host status fact
      set_fact:
        host_status: >
          {{ 'REACHABLE' if ping_result is succeeded else 'UNREACHABLE' }}

    - name: Add host status to global fact
      ansible.builtin.set_fact:
        all_hosts_status: "{{ (all_hosts_status | default({})) | combine({inventory_hostname: host_status}) }}"
      run_once: true
      delegate_to: localhost

- name: Send connectivity report email (CSV format)
  hosts: localhost
  gather_facts: no
  vars:
    email_recipient: "recipient@example.com"
    email_subject: "Ping Connectivity Report - CSV Format"
  tasks:

    - name: Generate CSV formatted report
      set_fact:
        csv_report: |
          host,status
          {% for host, status in hostvars['localhost'].all_hosts_status.items() %}
          {{ host }},{{ status }}
          {% endfor %}

    - name: Send email with CSV connectivity report
      community.general.mail:
        host: 172.23.18.26
        port: 465
        username: ansible@upay.systems
        password: Upay@321
        to: m.jahangir.alam@ucb.com.bd
        subject: "Unbound Timer CSV Report"
        body: "Please find attached the unbound-anchor.timer status report in CSV format."
        secure: always
        subtype: "csv"
