---
- name: Ping all Linux hosts and collect detailed status
  hosts: all
  gather_facts: no
  tasks:

    - name: Try to ping the host
      ansible.builtin.ping:
      register: ping_result
      ignore_errors: yes

    - name: Determine detailed status
      set_fact:
        detailed_status: >-
          {% if ping_result is succeeded %}
            REACHABLE
          {% elif ping_result.unreachable is defined and ping_result.unreachable and 'Invalid/incorrect password' in ping_result.msg %}
            AUTHENTICATION FAILED
          {% elif ping_result.msg is defined and ('Permission denied' in ping_result.msg) %}
            AUTHENTICATION FAILED
          {% elif ping_result.msg is defined and 'Connection refused' in ping_result.msg %}
            CONNECTION REFUSED
          {% elif ping_result.msg is defined and ('Timeout' in ping_result.msg or 'timed out' in ping_result.msg) %}
            TIMEOUT
          {% else %}
            UNREACHABLE
          {% endif %}

    - name: Set CSV line for each host
      set_fact:
        ping_info_line: "{{ inventory_hostname }},{{ detailed_status }}"

- name: Combine CSV Report on Controller
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    csv_file_path: "./detailed_ping_report.csv"
    email_recipient: "m.jahangir.alam@ucb.com.bd"
    smtp_host: "172.23.18.26"
    smtp_port: 465
    smtp_user: "ansible@upay.systems"
    smtp_password: "Upay@321"
  tasks:

    - name: Build CSV from all hosts
      set_fact:
        csv_report: |
          Host,Status
          {% for host in groups['all'] %}
          {{ hostvars[host].ping_info_line | default(host + ',UNKNOWN') }}
          {% endfor %}

    - name: Save CSV report to file
      copy:
        content: "{{ csv_report }}"
        dest: "{{ csv_file_path }}"

    - name: Send CSV report as email attachment
      community.general.mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user }}"
        password: "{{ smtp_password }}"
        to: "{{ email_recipient }}"
        subject: "Detailed Reachability CSV Report"
        body: "Please find attached the reachability status report with detailed reasons."
        attach:
          - "{{ csv_file_path }}"
        secure: always
