---
- name: Gather OS info and send via email
  hosts: all
  gather_facts: true
  tasks:
    - name: Save OS info to file
      copy:
        content: |
          Host: {{ inventory_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Kernel: {{ ansible_kernel }}
          Architecture: {{ ansible_architecture }}
        dest: "/tmp/{{ inventory_hostname }}_os_info.txt"

    - name: Fetch the file to control node
      fetch:
        src: "/tmp/{{ inventory_hostname }}_os1_info.txt"
        dest: "./os_reports/"
        flat: yes

- name: Send email with report
  hosts: localhost
  tasks:
    - name: Send mail with attachment
      community.general.mail:
        host: 172.23.18.26
        port: 465
        username: ansible@upay.systems
        password: Upay@321
        to: jahangir.alam@upaybd.com
        subject: "OS Info Report"
        body: "Please find attached the OS information report."
        attach:
          - "./os_reports/{{ inventory_hostname }}_os1_info.txt"
