---
- name: Gather OS info
  hosts: all
  gather_facts: true
  tasks:
    - name: Get last Windows Update
      win_shell: |
        Get-HotFix | Sort-Object -Property InstalledOn -Descending | Select-Object -First 1
      register: win_updates

    - name: Get Linux last update date (Debian/Ubuntu)
      shell: grep " upgrade " /var/log/dpkg.log | tail -1
      register: linux_update_dpkg
      when: ansible_os_family == "Debian"

    - name: Get Linux last update date (RedHat/CentOS)
      shell: grep Updated /var/log/yum.log | tail -1
      register: linux_update_yum
      when: ansible_os_family == "RedHat"

    - name: Get macOS last software update
      shell: defaults read /Library/Receipts/InstallHistory | grep -A 3 installDate | tail -n 4
      register: mac_update
      when: ansible_system == "Darwin"
      
    - name: Collect OS info in a fact
      set_fact:
        os_info_report: |
          Host: {{ inventory_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Kernel: {{ ansible_kernel }}
          Architecture: {{ ansible_architecture }}
          Hostname: {{ ansible_hostname }}
          Last Update: {{ linux_update_dpkg.stdout }}
          
    - name: Add OS info to central file (delegated to localhost)
      delegate_to: localhost
      run_once: true
      vars:
        reports: "{{ hostvars | dict2items | map(attribute='value.os_info_report') | join('\n\n') }}"
      copy:
        content: "{{ reports }}"
        dest: "./os_info_report.txt"

- name: Send OS info email
  hosts: localhost
  tasks:
    - name: Email report
      community.general.mail:
        host: 172.23.18.26
        port: 465
        username: ansible@upay.systems
        password: Upay@321
        to: jahangir.alam@upaybd.com, m.jahangir.alam@ucb.com.bd
        subject: "OS Info Report"
        body: "Attached is the full OS information report for all servers."
        attach:
          - "./os_info_report.txt"
